### ISSUE TITLE
PATCH /session/account/profile: "404 Admins have no profiles" error

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#103]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

We differentiate between normal user accounts that you can sign up for with `PUT /session/account` and admin accounts which are configured in the app configuration. The latter have no account or profile, they are only used to manage other accounts and other app settings.

`PATCH /session/account/profile` is already implemented correctly, the only problem is that we currently respond with a `403` status code, although after discussing it we agreed that `404` would be the better error code here.

### :dart: The goal

For admin users, `PATCH session/account/profile` should respond with `404 Not found` and the error message "Admins have no profiles"

### :clipboard: Step by Step

- [x] claim this issue (@bryanbierce)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Update the assertion in [https://github.com/hoodiehq/hoodie-server-account/blob/455350176c87a53e1eab8ae849370b1938cfbb58/tests/integration/routes/profile/patch-profile-test.js#L112-L114) to test for `404` and the desired error message
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PATCH /session/account/profile error for admins`
- [x] Start a Pull Request #119 
- [x] Implement :) 
- [x] Make sure tests pass. Commit with `fix(routes): PATCH /session/account/profile error for admins`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by bryanbierce** [comment]
Hey I'd love to take this issue if it's still open :)

**Comment by gr2m** [comment]
Yes it is, welcome @bryanbierce

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie-server-account/pull/119. Released as [v2.6.15](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.15). Thanks Bryan and welcome to Hoodie :tada: 

I’ve invited you to the Hoodie Contributors team, you should see an invite on https://github.com/hoodiehq

Let me know if you’d like to keep contributing, I’m sure we can find something :)

**Comment by bryanbierce** [comment]
Thanks! I’d love to keep contributing. If you have anything in particular that you know no one is tackling or you think would be a good place to start diving in deeper I’m game.

**Comment by gr2m** [comment]
Hey Bryan we run into an interesting bug here: 
https://github.com/hoodiehq/hoodie-server-account/pull/129

make sure to rebase Jay’s fork on latest master first, and then it’s about to find out where the `400` error comes from, it should be 401. Just comment in the thread if you want to look into it. I’m happy to help if you have any questions
