### ISSUE TITLE
README: fix anchor link

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#120]
### :bug: The Bug

<img width="990" alt="screen shot 2016-03-13 at 21 08 41" src="https://cloud.githubusercontent.com/assets/39992/13732770/de2ef7fc-e95f-11e5-9f2c-fdd4d7c318ed.png">

In the [README of this repository](https://github.com/hoodiehq/hoodie-account-server), you see a weird looking `[Constructor](#constructor)` in the [api.sessions.add() section](https://github.com/hoodiehq/hoodie-server-account/tree/master/api#apisessionsadd). This is meant to be a link to the [Constructor section](https://github.com/hoodiehq/hoodie-server-account/tree/master/api#constructor), but GitHub does not interpret the Markdown Syntax inside the table.

### :dart: The goal

Replace the faulty `[Constructor](#constructor)` part in the `README.md` file with the HTML code for an anchor link to `#constructor`.

### :clipboard: Step by Step

- [ ] claim this issue (comment below)
- [ ] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md)
- [ ] Edit the `README.md` file. Replace the Markdown code for the link to Contructor in the api.sessions.add() section with HTML code
- [ ] Commit the change `docs(README): Constructor link in api.sessions.add()`
- [ ] Start a Pull Request.  
<small>(If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request)</small>
- [ ] Done :+1: Comment below to ask for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by texassiga** [comment]
claiming this issue..

**Comment by KaLaUnlimited** [comment]
Claiming issue

**Comment by gr2m** [comment]
this has been resolved meanwhile
