### ISSUE TITLE
POST /accounts Add test for 401, "Session invalid" if user is not an admin

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#124]
<a href="https://ti.to/hoodie/dc-meet-the-hoodies"><img width="664" alt="This issue is prepared for our Meet The Hoodies event in Washington DC on March 20th" src="https://cloud.githubusercontent.com/assets/39992/13901581/169ced44-edff-11e5-93d7-aaf3ef673fbc.png"></a>

### :dart: The goal

When running `npm test` then all specifications from the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#) that we implement
should be tested. Creating an account with [POST /accounts](http://docs.accountjsonapi.apiary.io/#reference/admins/user-account-collection/create)
defines a `401` response with a `Session invalid` error message. This can occur
the currently signed in user is not an admin. We do not test that yet, and the
goal of this issue is to create this test to make sure the server behaves correctly
and does not accidentally break in future.

### :clipboard: Step by Step

- [x] claim this issue (comment below)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Implement test in [tests/integration/routes/accounts/post-accounts-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/a2a965cc38693da53865e21a720da2183265c630/tests/integration/routes/accounts/post-accounts-test.js#L66-L69). Compare tests in [tests/integration/routes/account/get-account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/a2a965cc38693da53865e21a720da2183265c630/tests/integration/routes/account/get-account-test.js#L62-L95): What we need here is kinda the reverse
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): POST /accounts -> 401 for non-admin`
- [ ] Start a Pull Request. Mention `closes #124` in the description.  
      If this is your first, welcome :tada: :smile:
      [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
      on how to send a pull request
- [ ] Done :+1: Comment below to ask for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by JayWIlsonJr** [comment]
I will look into this.

**Comment by dwouda27** [comment]
PayPal.Me/dwouda/25

**Comment by gr2m** [comment]
Hey @JayWIlsonJr it’s been a while, how are things going? How is the new career going? 

I’ll move this issue to our [camp repository](https://github.com/hoodiehq/camp/issues), this is our central place now where we create issues like this one. If you are still interested in contributing, I’d be happy to help find something interesting for you to work on :)

Greetings from LA 👋
