### ISSUE TITLE
GET /accounts Add test for 401, "Session invalid" if user is not an admin

### ISSUE THREAD

**Issue by codyzu** [hoodiehq/hoodie-account-server#136]
Write test and implement 'Not an admin' in `tests/routes/accounts/get-accounts-test.js` as required by issue #83 

I will work on this if it looks good for the team...

**Comment by gr2m** [comment]
Awesome! We’ve invited you to the Hoodie Contributors Team, you should see an invitation here: https://github.com/hoodiehq. When you join you can assign your self to issues like this in future :)

**Comment by gr2m** [comment]
closed by https://github.com/hoodiehq/hoodie-account-server/issues/137. That was great work, merci bien!
