### ISSUE TITLE
README: setup instructions

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#138]
### :bug: The Bug

In the [setup instructions in tests/README.md](https://github.com/hoodiehq/hoodie-account-server/blob/master/tests/README.md) we tell the user to clone the repository using `git clone git@github.com:hoodiehq/hoodie-account-server.git`. But GitHub itself recommends the `https://` protocol instead of the `git@` which is SSH (see [which remote should I use](https://help.github.com/articles/which-remote-url-should-i-use/)).

### :dart: The Goal

Replace the `git clone git@github.com:hoodiehq/hoodie-account-server.git` with `https://github.com/hoodiehq/hoodie-account-server.git` in the `tests/README.md`

### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request

- [x] claim this issue (@huzaifafaruqui)
- [x] Clone the repository to your computer
- [x] Edit the `tests/README.md` file.
- [x] Commit the change `docs(tests): fixed git clone URL`
- [x] Start a Pull Request #153 
- [x] Done :+1: Comment below to ask for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by huzaifafaruqui** [comment]
hey can I work on this issue?

**Comment by gr2m** [comment]
oh yes absolutely, all yours @huzaifafaruqui :)

**Comment by gr2m** [comment]
Thanks @huzaifafaruqui, that was perfect :ok_hand: welcome to Hoodie! Are you on twitter? We like giving new contributors a shout out, if you don’t mind? 

Let me know if you want to keep contributing, we're happy to help you find something. Best is to join our [Hoodie chat](http://hood.ie/chat). You can also send me a direct message in there, I’m `@gregor`.

Have a fantastic weekend!
