### ISSUE TITLE
Standardize PouchDB error handling

### ISSUE THREAD

**Issue by codyzu** [hoodiehq/hoodie-account-server#147]
As discussed in the (hidden) comments of PR #137 we should standardize the way we check for errors thrown by PouchDB.

Sometimes we compare the error.name and sometimes error.status. While comparing against the actual error object thrown by PouchDB might be the most descriptive option, this creates a dependency (on PouchDB) that we don't want to add to this project. It seems comparing by status code is the most robust and feasible (and therefore best!) option.

TODO: refactor error handling to compare against status code when possible (avoiding error.name).

**Comment by gr2m** [comment]
+1 for comparing with Status code. Thanks Cody

**Comment by codyzu** [comment]
This was resolved when #148 was merged.
