### ISSUE TITLE
ignore cookie headers from all requests

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#17]
Although hoodie-server-acocunt does not set any cookies, there are cases where a cookie might be set and cause very hard bugs. Cookies are scoped by host, not including the port number. So if the API from `hoodie-server-account` is accessible at http://localhost:4000/api/account and CouchDB is at http://localhost:5984, CouchDB’s `AuthSession` cookie will be sent to http://localhost:4000/api/account as well.

We don’t proxy requests at this point, but I'd say we should do this anyway for sanity

Simple fix is: remove all cookie headers in all requests. To achieve that, [hapi’s `server.ext`](http://hapijs.com/api#serverextevent-method-options) method can be used to hook into [hapi’s request lifecycle](http://hapijs.com/api#request-lifecycle). Make sure to use the `sandbox: 'plugin'` option on `server.ext`. 

- [ ] Start Pull Request to claim the issue and start discussion
- [ ] write a failing tests for any request sending a cookie
- [ ] fix test
- [ ] review & merge

**Comment by sebbel** [comment]
Hey gregor, I am interested in this task. Currently looking into the hapi docs to find informations about cookies and the request lifecycle. I understand that I would need to create a hook in server,ext that would augment onRequest to delete cookie headers.

**Comment by gr2m** [comment]
great, all yours :)

**Comment by sebbel** [comment]
tyvm Gregor

Am Samstag, 2. April 2016 schrieb Gregor Martynus :

**Comment by gr2m** [comment]
Congrats @sebbel, great work :clap: 

You are part of the Hoodie Contributors team, that allows you to create branches on https://github.com/hoodiehq/hoodie-account-server, you can then send PRs from these branches. That will make the git things simpler, and will also allow us to rebase your PR for you before merging :)
