### ISSUE TITLE
Generate standard UUIDs for account IDs

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#173]
https://github.com/hoodiehq/hoodie-account-server/blob/master/api/accounts/add.js#L13-L15

follow the convention, e.g. see https://en.wikipedia.org/wiki/Universally_unique_identifier. You can for example use [uuid.v4()](https://www.npmjs.com/package/uuid) for that

**Comment by ohiock** [comment]
Hey @gr2m - looks like this was resolved in #185

**Comment by gr2m** [comment]
oh yes, thanks! Totally missed to close this issue when I created https://github.com/hoodiehq/camp/issues/31 👍
