### ISSUE TITLE
Add 409 response for Admin account.delete

### ISSUE THREAD

**Issue by mikehedman** [hoodiehq/hoodie-account-server#24]
If an admin requests the deletion with a bad id, currently the only responses available are 204 and 401, it seems like a 409 is also possible as in the update function.

**Comment by gr2m** [comment]
This can be fixed in https://github.com/hoodiehq/account-json-api

**Comment by gr2m** [comment]
Hey @mikehedman I know it’s been a long while, but do you remember when the `409` response would be appropriate? For the update function, the server responds with `409` if the passed type or id attribute don’t match `'account'` or the id from the URL. But DELETE requests don’t have a body, so I can’t think of how case when the server would respond with `409`. It’s not in the spec either: http://jsonapi.org/format/#crud-deleting

**Comment by mikehedman** [comment]
@gr2m - I looked at the spec, and the formal definition of what a 409 is supposed to represent, and I agree that it doesn't make sense for a DELETE request.  I'll close this issue.
