### ISSUE TITLE
adjust api.session.add to new API

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#26]
https://github.com/hoodiehq/hoodie-server-account/tree/master/api#apisessionsadd

<table>
  <thead>
    <tr>
      <th>Argument</th>
      <th>Type</th>
      <th>Description</th>
      <th>Required</th>
    </tr>
  </thead>
  <tr>
    <th align="left"><code>options.username</code></th>
    <td>String</td>
    <td>-</td>
    <td>Yes</td>
  </tr>
  <tr>
    <th align="left"><code>options.auth</code></th>
    <td>Object</td>
    <td>Can be <code>username</code> and <code>password</code> or <code>session</code>. If not set, will use <code>options.auth</code> from <a href="#constructor">Constructor</a></td>
    <td>No</td>
  </tr>
</table>

```js
admin.sessions.add({
  username: 'pat'
}).then(function (sessionProperties) {
  var bearer = sessionProperties.id
  var username = sessionProperties.account.username
}).catch(function (error) {
  console.error(error)
})
```

**Comment by codyzu** [comment]
@gr2m as we discussed in #80 this needs to authenticate against options.auth.session...

Creating the new session seems simple (already implemented!), but I'm unsure about the `auth`? This should be authenticating for an admin?

The doc says:
> Admins can create a session for any user.

But api.sessions does not have a reference to the initialized `admins` object... How can I validate auth object?

Thanks!

**Comment by gr2m** [comment]
You can validate a session the same way that [sessions.find does it](https://github.com/hoodiehq/hoodie-account-server/blob/0c9415c/api/sessions/find.js#L14-L22) – retrieve the user’s document and validate the session id using the server secret and user’s salt property

**Comment by codyzu** [comment]
great. Thanks @gr2m! I'll take a look in a few hours.
