### ISSUE TITLE
Usernames with capital letters fail to authenticate

### ISSUE THREAD

**Issue by alterx** [hoodiehq/hoodie-account-server#271]
I've been playing around with the account package and noticed that while creating users with capital letters in their usernames is allowed when the user attempts to log in, this package lowercases the username.

https://github.com/hoodiehq/hoodie-account-server/blob/eb1eeae6d749963a948be331dac83dfbd7e9958c/routes/session.js#L42

This causes a 404 error (of course, there's no such user) that stops the sign in process. Is there any particular reason for this? If it is, the creation of users with capital letters shouldn't be allowed, If it isn't, we could just remove this line.

**Comment by gr2m** [comment]
> the creation of users with capital letters shouldn't be allowed

💯 

That’s a legit bug, can you take a stab at a PR? Let me know if you need any pointers or guidance :)

**Comment by alterx** [comment]
Sure! 
Just to be clear are we going with option a (not allowing the creation of users with capital letters) or b (fixing this line)?

**Comment by gr2m** [comment]
a – not allowing the creation of users with capital letters

**Comment by alterx** [comment]
Gotcha :)
