### ISSUE TITLE
Implement events

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#35]
- [ ] api.accounts events
- [ ] api.sessions events
- [ ] api.requests events

**Comment by stevemasta34** [comment]
Can I get a little more description on what these desired "events" are?

**Comment by gr2m** [comment]
Hey @stevemasta34, these events are about the account JavaScript API that we use within the route handlers, but also expose at `server.plugins.account.api`. You can see the full documentation at https://github.com/hoodiehq/hoodie-server-account/blob/master/api/README.md, the events are described here: https://github.com/hoodiehq/hoodie-server-account/blob/master/api/README.md#events

We can start with the `api.accounts` events, everything should be in place to make them work. Sessions are blocked because we currently do not persist them, we could only trigger an "add" event. Requests are also not persisted yet, but we plan to implement that soon. 

So, what we’d want to do here is to use [PouchDB’s changes feed](https://pouchdb.com/api.html#changes) to emit `add`, `update` or `remove` events, which also always trigger a `change` event. The API should look like this

```js
api.accounts.on('add', function(account) {})
api.accounts..on('update', function(account) {})
api.accounts..on('remove', function(account) {})
api.accounts..on('change', function(eventName, account) {})
```

Makes sense?

**Comment by stevemasta34** [comment]
https://medium.com/keep-learning-keep-growing/6-ways-to-recover-from-an-unproductive-day-920f89724983#.95nytek24

**Comment by stevemasta34** [comment]
Yes this make a lot of sense. I'll start a local branch, and if I get any headway (or stuck) I'll start the PR.

**Comment by janl** [comment]
Heya @stevemasta34: did you get anywhere with this?

If wanna share some in-progess work, I‘d be happy to help :)

**Comment by stevemasta34** [comment]
Hey @janl my work life has kind of taken over my personal life, so my progress has been minimal; my free time disappeared. You're more than welcome to take the lead on this one, and I'll tag in this weekend.

**Comment by gr2m** [comment]
moved to https://github.com/hoodiehq/hoodie-account-server-api/issues/3 and https://github.com/hoodiehq/hoodie-account-server-api/issues/9
