### ISSUE TITLE
re-enable coverage

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#37]
undo: https://github.com/hoodiehq/hoodie-server-account/commit/fef841676380fe80c42a7dc627f55e8ec76c99fb & https://github.com/hoodiehq/hoodie-server-account/commit/d8a5f87c520e3c72586358a1fb9fefb18e05d076, then fix the tests, and update the badges in the README

**Comment by codyzu** [comment]
I'll take a look at this... strange that some tests fail with coverage. I'll try to investigate.
