### ISSUE TITLE
Implement username change

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#79]
### :bug: The bug

Currently, `PATCH /session/account` request with `{"username": "newusername"}` results in an update of `/_users/org.couchdb.user:oldusername`. The `username` property gets set to `newusername`. 

The account update within the `PATCH /session/account` route handler is implemented [here](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/routes/account.js#L135-L140). The implementation of the account update simply loads the user account document from CouchDB and merges in the changes [here](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/api/accounts/update.js#L15).

### :dart:  How it should be

1. copy the `/_users/org.couchdb.user:oldusername` to `/_users/org.couchdb.user:newusername`. In the new document, set `name` to the new username. Do _**not**_ set the `username` property. Leave all the other properties like `salt` and `derived_key` untouched.
2. delete `/_users/org.couchdb.user:oldusername`

### :clipboard: Step by step on how to fix :)

- [x] claim this issue (@codyzu)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] create a new test for the `PATCH /session/account` route below this one: [tests/integration/routes/account-test.js#L212-L278](https://github.com/hoodiehq/hoodie-server-account/blob/72d7fbd75b0093afc120b9c6ac72d9cdfeca16ea/tests/integration/routes/account-test.js#L212-L278). Name it `PATCH /session/account username change`. The existing account doc should be removed and the new created with the same `POST /_bulk_docs` request. The delete of the existing document should besides the `"_deleted": true` also add a property `"renamedTo": "newusername"`. The new doc must not have a `"username"` property. Make sure that tests fail when your run `npm  test`
- [x] commit with `test: username change`. Feel free to push your work in progress if you have any questions. It’s easiest to discuss directly in a PR
- [x] start a Pull Request: #155
- [x] Implement the fix
- [x] commit with `fix: username change`
- [x] Yay :tada: comment below and let us know that your PR is ready for review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by gr2m** [comment]
Added "first-timers-only" as in: your first contribution to Hoodie :)

**Comment by alisabzevari** [comment]
Can I pick this one?

**Comment by gr2m** [comment]
sure, good luck Ali :+1:

**Comment by gr2m** [comment]
@alisabzevari are you still loking into this one?

**Comment by alisabzevari** [comment]
@gr2m Sorry. I had busy days. I will make a progress in the next few days.

**Comment by gr2m** [comment]
ping @alisabzevari, how is it looking?

**Comment by codyzu** [comment]
PR #155 ready!

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie-account-server/pull/155
