### ISSUE TITLE
PATCH /session/account: respond with `x-set-session` header

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#80]
related to https://github.com/hoodiehq/hoodie-client-account/issues/75

### :bug: The problem

Hoodie’s session ID gets invalidated if a username or password gets changed.

### :dart: How to fix

In order to update the session id on the client, we want to set the `x-set-session` header with a new session ID to each `PATCH /session/account` 200 response.

### :clipboard: Step by Step

- [x] claim this issue (@codyzu)
- [ ] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [ ] uncomment the test at [tests/integration/routes/account/patch-account-test.js Line 147](https://github.com/hoodiehq/hoodie-account-server/blob/719af8f494bf16d07fd995c6af2d357013ff2adc/tests/integration/routes/account/patch-account-test.js#L147), see my [explanation below](https://github.com/hoodiehq/hoodie-account-server/issues/80#issuecomment-201894138)
- [ ] Make sure tests fail when you run `npm test`. Commit with `test: x-set-session header`
- [ ] Start a Pull Request.  
<small>(If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request)</small>
- [ ] Implement :) You can set a custom response header with `reply(body).header('x-custom', 'some-value')`
- [ ] Make sure tests pass. Commit with `feat: x-set-session header`
- [ ] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by gr2m** [comment]
Added "first-timers-only" as in: your first contribution to Hoodie, not necessarily to Open Source in general :)

**Comment by artivilla99** [comment]
Can I take this?

**Comment by gr2m** [comment]
Absolutely :)

**Comment by gr2m** [comment]
Hey @artivilla99, are you still working on this?

**Comment by gr2m** [comment]
Hey @artivilla99, do you still want to look into that issue? If not no problem, I’ll free it up from somebody else

**Comment by artivilla99** [comment]
Hi @gr2m I just started new work and then got distracted learning stuff on nodeschool. Free it up and if I manage to figure it out, i'll send a PR. If someone get's to it before me all good!

**Comment by gr2m** [comment]
Okay Thanks for the update. Good luck with the the new  work :)

**Comment by artivilla99** [comment]
Still can’t quite wrap my head around it but the fs (file system) seems to have changed as well for this issue. Is this ticket still valid? Am I trying to mock a new user in my tests?

**Comment by gr2m** [comment]
I’m sorry for the confusion, a few things changed since I created this issue, but it’s still valid. I’ve prepared the test for you and updated the issue description, I hope it helps? Please let me know if you have any farther questions :)

Here is an explanation of what I did it: 

I’ve prepared an assertion to to check for `response.headers['x-set-session']` to the [`PATCH /session/account` test](https://github.com/hoodiehq/hoodie-account-server/blob/4f72ed2/tests/integration/routes/account/patch-account-test.js#L133-L150). For username `'pat-doe'`, salt `'salt123'`, secret `'secret'` and timeout `1209600`, [the session id should be `'cGF0LWRvZToxMjc1MDA6zEZsQ1BuO-W8SthDSrg8KXQ8OlQ'`](https://tonicdev.com/gr2m/56c250ba10e8630c000c063c). `1209600` is the default timeout. Make sure to use `lolex` to mock (and restore) the `Date`, see how the `PUT /session` tests are doing it. This is necessary to simulate `Date.now()` to return `0` ([Jan 1st 1970](https://en.wikipedia.org/wiki/Unix_time)), so that when the expire timestamp gets calculated by adding 1209600 seconds, the result is always `1209600`.

**Comment by codyzu** [comment]
@gr2m I've started working on this... I have a question:

I need to implement the logic to calculate a new session id... can I add file like `/api/session/update.js` to implement this logic? Then in the routes/account PATCH, after updating the user, it can call session update? I'm not sure if the files exposed in `api` are fixed to a spec or something similar...

**Comment by codyzu** [comment]
@gr2m 2nd question:

Do we need to "renew" the session ID? Or just decode the "old" session, replace the name, and encode the "new" session ID?

**Comment by gr2m** [comment]
> I need to implement the logic to calculate a new session id

You can use (server.plugins.account.api.sessions.add())[https://github.com/hoodiehq/hoodie-account-server/tree/master/api#apisessionsadd]

> Do we need to "renew" the session ID? Or just decode the "old" session, replace the name, and encode the "new" session ID?

Yeah that sounds right. We should validate the old session id, then generate a session id for the new username and return that in the `x-set-session` header

**Comment by codyzu** [comment]
@gr2m 

> You can use (server.plugins.account.api.sessions.add())[https://github.com/hoodiehq/hoodie-account-server/tree/master/api#apisessionsadd]

I don't think this call will work because the current implementation validates the password sent in the options. If I understand the PATCH /session/account, we might be changing the username OR password so it is not sure that I will always have access the user's password (i.e. if they only change their username).

The spec says that server.plugins.account.api.sessions.add() can accept session, but I don't think the current implementation supports this...

Q: I'm guessing I shouldn't change the functionality too much (i.e. adding a new "update" function to server.plugins.account.api.sessions). I need to implement the logic for the sessions.add() to take a session, as described in your link to the spec?

**Comment by codyzu** [comment]
@gr2m 

So I think I have narrowed my problem to this: [server.plugin.account.api.sessions.add](https://github.com/hoodiehq/hoodie-account-server/tree/master/api#apisessionsadd) says the `options.auth` param should be:

> Can be username and password or session. If not set, will use options.auth from Constructor

However, in `api/sessions/add.js` the `addSession` function uses `options.password` no mention of `options.auth` or `options.auth.session` etc...

My feeling is, we need to create a new issue to correctly implement the session.add (optionally accepting a session for the auth). Once that exists, it should be simple to have the PATCH /session/account route add a new session using the old session for auth?

Maybe I'm missing something :-)

**Comment by gr2m** [comment]
great work @codyzu, I think you are absolutely right. The [current version of sessions.add](https://github.com/hoodiehq/hoodie-account-server/blob/736e27a/api/sessions/add.js) does not implement authentication with `options.auth.session`. I agree we can make a separate issue for it. Feel free to open one and assign it to yourself as a follow up to this discussion. If you’re busy and would like this to move forward, I can make the issue and reach out for help, I’d be happy to

**Comment by codyzu** [comment]
@gr2m I found issue #26 already exists. Should I just work from there?

**Comment by gr2m** [comment]
yeah sounds good, thanks :+1:

**Comment by gr2m** [comment]
done via https://github.com/hoodiehq/hoodie-account-server/pull/152
