### ISSUE TITLE
GET /session: 404 should be 401

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-account-server#95]
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

The handler for the  [GET /session route](https://github.com/hoodiehq/hoodie-server-account/blob/61798c9/routes/session.js#L86-L133) currently returns 404 if a session is invalid.

### :dart: The goal

But in our [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/session/check-session) we define `401` as the error code for an invalid session, so the correct server response should be `401 Unauthorized – Session invalid`

### :clipboard: Step by Step

- [x] claim this issue (@hyperperforator)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] We currently test for a `404` status [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/tests/integration/routes/session/get-session-test.js#L60) and [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/tests/integration/routes/session/get-session-test.js#L104-L106). Replace it with `401`. Also: `.title` should be `'Unauthorized'` and add an assertion for `.detail` which must be `'Session invalid'`
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test: GET /session: 404 should be 401`
- [x] Start a Pull Request.  Add `fixes #95` to the description.  
<small>(If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request)</small>
- [x] Implement :) Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/routes/session.js#L116-L118) and for comparison [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/routes/session.js#L62-L67)
- [x] Make sure tests pass when you run `npm test`. Commit with `fix: GET /session: 404 should be 401`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by hyperperforator** [comment]
This looks like a great place to try my first public PR.... I'm going to give it a go! :)

**Comment by nickcolley** [comment]
Woop, thanks @hyperperforator. I've assigned you, let us know if you need any help!

**Comment by ederribeiro** [comment]
This issue is already assigned? I want to solve this...

**Comment by gr2m** [comment]
@ederribeiro yes @hyperperforator got this one, but this one’s yours: https://github.com/hoodiehq/hoodie-server-account/issues/101#issuecomment-192918166 :+1:

**Comment by gr2m** [comment]
@hyperperforator are you still working on this one?

**Comment by hyperperforator** [comment]
Oooh, yes! Sorry, I'll take a look tonight. Was stuck but can't remember why... I'll be back soon!

**Comment by gr2m** [comment]
@hyperperforator ping :bell: :) No biggie if you don’t have time, we can free it up and we can find something else you can work on if you have more time again :)

**Comment by hyperperforator** [comment]
Hey! Just did this today, stand by for my first pull...

**Comment by hyperperforator** [comment]
Hey hey,

I've just submitted my PR! Let me know if I got it working properly :) 🔥
https://github.com/hoodiehq/hoodie-account-server/pull/142
